jpeg_quality = 80

[serve]
as = "WEBP"
quality = 90.0

[tags]

# File uploads
[tags.attachments]
max_size = 20000000
serve_if_field_present = ["object_id", "message_id"]

# User avatars
[tags.avatars]
max_size = 4000000
restrict_content_type = "Image"
serve_if_field_present = ["object_id", "user_id"]

# User profile backgrounds
[tags.backgrounds]
max_size = 6000000
restrict_content_type = "Image"
serve_if_field_present = ["object_id", "user_id"]

# Banners
[tags.banners]
max_size = 6000000
restrict_content_type = "Image"
serve_if_field_present = ["object_id", "server_id"]

# Emoji
[tags.emojis]
max_size = 500000
restrict_content_type = "Image"
serve_if_field_present = ["object_id"]
use_ulid = true

# Channel and server icons
[tags.icons]
max_size = 2500000
restrict_content_type = "Image"
serve_if_field_present = ["object_id"]
